version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  web:
    build: ./Docker/web
    ports:
      - '8080:80'
    volumes:
      - ./client:/var/www/html
    depends_on:
      - db
